alias agitVoncGitHub='alias git="${H}/sbin/wgit u VonC,vonc@laposte.net,github.com"'
alias agitBjensenItsvcprdgit='alias git="${H}/sbin/wgit u bjensen,bjensen@example.com,itsvcprdgit.world.company,bjensen"'
alias agitBjensenItsvc='alias git="${H}/sbin/wgit u bjensen,bjensen@example.com,itsvc,bjensen"'
alias agitGitoliteadm='alias git="${H}/sbin/wgit u gitoliteadm,gitoliteadm@mail.com,itsvc"'
alias gl='git lga -20 --branches'
