#! /bin/bash

tomcat="${H}/tomcat"
keystore="${tomcat}/keystore.jks"
apache="${H}/apache"
pkcs12="${tomcat}/mycert.p12"

if [[ ! -e "${keystore}" ]]; then
  openssl pkcs12 -export -in "${apache}/crt" -inkey "${apache}/key" -out "${pkcs12}" -name tomcat -passout pass:changeit
  keytool -importkeystore -srckeystore "${pkcs12}" -srcstoretype PKCS12 -destkeystore "${keystore}" -srcstorepass changeit -deststorepass changeit -alias tomcat
fi
