#!/bin/bash

cp -f "${H}/.cpl/src/git/contrib/credential/netrc/git-credential-netrc" "${HULA}/git/libexec/git-core"
ln -fs "${HULA}/git/libexec/git-core/git-credential-netrc" "${H}/.gnupg/git-credential-netrc"

f="${HULA}/git/libexec/git-core/git-credential-netrc"

gen_sed -i "s;/usr/bin/perl;${H}/bin/perl;g" "${f}"
gen_sed -i "s;\\\.gpg;\\\.(asc|gpg);g" "${f}"
gen_sed -i "s;gpg --decrypt;${HS}/gpg --batch -q --decrypt;g" "${f}"
gen_sed -i '/~\/\.netrc.gpg/ a \\t\t\t\t   ~\/\.netrc.asc' "${f}"

t=$(grep "my $entry_without_num_port;" "${f}")
if [[ "${t}" == "" ]]; then
  gen_sed -i '0,/my \$query = shift @_;/s/my \$query = shift @_;/my $query = shift @_;\n    my $entry_without_num_port;/' "${f}"
fi

t=$(grep "Match potential on host" "${f}")
if [[ "${t}" == "" ]]; then
  gen_sed -i 's/unless (\$query->{\$check} eq \$entry->{\$check}) {/if ($check eq "host" \&\& $query->\{$check\} =~ \/(.*?):\\d+\/ \&\& $1 eq $entry->\{$check\}) {\n\t\t\t\t\t$entry_without_num_port = $entry;\n\t\t\t\t\tlog_debug("Match potential on host %s", $query->\{$check\})\n\t\t\t\t\}\n\t\t\t\tunless ($query->\{$check\} eq $entry->\{$check\} || ( $check eq "host" \&\& $entry_without_num_port) ) \{\n\t\t\t\t\t$entry_without_num_port = undef;/' "${f}"
fi
