#!/bin/bash

cp -f "${H}/.cpl/src/git/contrib/credential/netrc/git-credential-netrc" "${HULA}/git/libexec/git-core"
ln -fs "${HULA}/git/libexec/git-core/git-credential-netrc" "${H}/.gnupg/git-credential-netrc"

f="${HULA}/git/libexec/git-core/git-credential-netrc"

gen_sed -i "s;/usr/bin/perl;${H}/bin/perl;g" "${f}"
gen_sed -i "s;\\\.gpg;\\\.(asc|gpg);g" "${f}"
gen_sed -i "s;gpg --decrypt;${HS}/gpg --batch -q --decrypt;g" "${f}"
gen_sed -i '/~\/\.netrc.gpg/ a \\t\t\t\t   ~\/\.netrc.asc' "${f}"
