#!/bin/bash

g="${H}/.gnupg"

if [[ $(gpg2 -k | grep "Project External Reader") == "" ]]; then
  # generate activity for entropy
  # similar to http://serverfault.com/a/471418/783
  # (also check out https://bugs.launchpad.net/ubuntu/+source/gnupg/+bug/706011)
  # or https://github.com/bartmeuris/apt-packageserver/blob/master/packageserver.sh
  gpg2 --batch --yes --no-tty --passphrase "projextrdrpp1" --gen-key "${g}/projextrdr.unattended" & 
  # http://stackoverflow.com/a/1911387/6309
  PID=$!
  a="go"
  while [[ "${a}" != "" ]]; do
    haveged -n 1g -f "${g}/tmp" | dd of=/dev/null
    a=$(ps -ef|grep "${PID}"|grep -v grep|grep gpg2)
  done
  rm -f "${g}/tmp"
fi

if [[ $(gpg2 -k | grep "Project External Reader") == "" ]]; then
  echo "No key generated for projextrdr"
  exit 1
fi

if [[ ! -e "${g}/projextrdr.privatekey.asc" ]]; then
  gpg --export-secret-keys --armor projextrdr > "${g}/projextrdr.privatekey.asc"
fi

if [[ ! -e "${g}/projextrdr.publickey.asc" ]]; then
    gpg --export --armor projextrdr > "${g}/projextrdr.publickey.asc"
fi

