#!/bin/bash

# generate activity for entropy
# similar to http://serverfault.com/a/471418/783
# (also check out https://bugs.launchpad.net/ubuntu/+source/gnupg/+bug/706011)
# or https://github.com/bartmeuris/apt-packageserver/blob/master/packageserver.sh
gpg2 --batch --yes --no-tty --passphrase "projextrdrpp1" --gen-key projextrdr.unattended & 
# http://stackoverflow.com/a/1911387/6309
PID=$!
a="go"
while [[ "${a}" != "" ]]; do
  haveged -n 1g -f "${H}/.gnupg/tmp" | dd of=/dev/null
  a=$(ps -ef|grep "${PID}"|grep -v grep|grep gpg2)
done
rm -f "${H}/.gnupg/tmp"
