#! /bin/bash
asrcline=$(wget --no-check-certificate -q -O - "http://www.postgresql.org/" | grep -e "release-")
#echo "asrcline='${asrcline}'"
pgsver="${asrcline%%</b*}"
#echo "pgsver: ${pgsver}"
pgsver="${pgsver##*b>}"
#echo "pgsver: ${pgsver}"
echo "http://ftp.postgresql.org/pub/source/v${pgsver}/"
