#!/bin/bash
fullFilePathOri="$1"
fullPathDst="$2"
fileOri="${fullFilePathOri##*/}"
fullPathOri="${fullFilePathOri%/*}"
if [[ "${fullPathOri}" == "${fullFilePathOri}" ]] ; then fullPathOri="." ; fi 
echo "-------"
#echo "fullFilePathOri='${fullFilePathOri}',"
#echo "fullPathDst='${fullPathDst}'"
#echo "fullPathOri='${fullPathOri}',"
#echo "fileOri='${fileOri}'"

function get_param_file() {
  local _filename=$2
  local filename="$1"
  local afilename="${H}/${filename}"
  if [[ ! -e "${afilename}" ]] ; then 
    afilename="${H}/../${filename}"
  fi
  eval $_filename="'${afilename}'"
}

fileDst="${fileOri%.tpl}"
if [[  "${fileDst}" == "${fileOri}" ]] ; then echo "name '${fileOri} MUST end with '.tpl'" ; exit 1 ; fi
#echo "fileDst='${fileDst}'"

fullFilePathDst="${fullPathDst}/${fileDst}"
echo cp -f "${fullFilePathOri}" "${fullFilePathDst}"
cp -f "${fullFilePathOri}" "${fullFilePathDst}"

gen_sed -i "s;@H@;${H};g" "${fullFilePathDst}"
gen_sed -i "s/@HOSTNAME@/$(hostname -s)/g" "${fullFilePathDst}"

#fqn=$(nslookup $(hostname -i)) ; fqn=${fqn##*name = } ; fqn=${fqn%.*}
fqn=$(host -TtA $(hostname -s)|grep "has address"|awk '{print $1}') ; if [[ "${fqn}" == "" ]] ; then fqn=$(hostname -s) ; fi
gen_sed -i "s/@FQN@/${fqn}/g" "${fullFilePathDst}"
fqnemail=${fqn/./@}
gen_sed -i "s/@EMAIL@/${fqnemail}/g" "${fullFilePathDst}"

get_param_file ".ports.ini" portini
while read line; do 
  port=(${line#*=})
  name=(${line%=*})
  # echo "${name} - ${port}"
  gen_sed -i "s;${name};${port};g" "${fullFilePathDst}"
done < "${portini}"

epoch=$(date +%s)
epoch=$((epoch+1000))
gen_sed -i "s/@EPOCH@/${epoch}/g" "${fullFilePathDst}"

ldapg=$(grep "@LDAP_" "${fullFilePathDst}")
# echo "ldapg ${ldapg}"
if [[ "${ldapg}" != "" ]] ; then
  get_param_file ".ldap" ldap
  if [[ -e "${ldap}" ]] ; then
    while read line; do
      ldapp=("${line#*=}")
      ldapn=(${line%%=*})
      # echo "ldap: ${ldapn} - ${ldapp}"
      gen_sed -i "s;${ldapn};${ldapp};g" "${fullFilePathDst}"
    done < "${ldap}"
  else
    gen_sed -i -n -e '/LDAP_START/{p; :a; N; /LDAP_END/!ba; s/.*\n//}; p' "${fullFilePathDst}"
    # gen_sed -i -n -e '/LDAP_START/{' -e 'p' -e ':a' -e 'N' -e '/LDAP_END/!ba' -e 's/.*\n//' -e '}' -e 'p' "${fullFilePathDst}"
    gen_sed -i "s; companyldap;;g" "${fullFilePathDst}"
  fi
  gen_sed -i "s;# LDAP_START;;g" "${fullFilePathDst}"
  gen_sed -i "s;# LDAP_END;;g" "${fullFilePathDst}"
fi
