#! /bin/bash

if [[ ! -e "${HB}/cpanm" ]]; then "${HSU}/cmd" cpanm "$@" ; exit 0 ; fi

homed=${H##*/}
if [[ ! -e "${H}/../.offline.${homed}" ]] ; then "${HSU}/cmd" cpanm "$@" ; exit 0 ; fi

# http://www.cyberciti.biz/faq/bash-iterate-array/arg
args=( "$@" )
# for arg in "${args[@]}"
nargs=${#args[*]}
for (( i=0; i<=$(( $nargs -1 )); i++ ))
do
  arg=${args[$i]}
  # http://stackoverflow.com/questions/6261126/modifying-a-parameter-pass-to-a-script-bash
  if [[ "${arg#*::}" != "${arg}" ]] ; then
    # http://stackoverflow.com/questions/13210880/replace-one-substring-for-another-string-in-shell-script
    name="${arg/::/-}"
    file=$(ls -rt1 "${H}/.cpl/src/_pkgs/pl/"|grep ${name}|tail -1)
    if [[ "${file}" == "" ]]; then echo "no offline tgz for '${arg}'"; exit 1; fi
    args[$i]="${H}/.cpl/src/_pkgs/pl/${file}" 
  fi
  # echo "${args[$i]}=>'${arg}'"
done
"${HSU}/cmd" cpanm "${args[@]}"
