#! /bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=${DIR%/*}
# echo DIR=$DIR
cd "${DIR}"
H="${DIR}"
source "${DIR}/.bashrc" --force
echo HOME=$HOME $H
# exit 0
case "$1" in
'start')
  "${H}/sbin/sshd" start
  if [[ -e "${H}/sbin/slapdd" ]] ; then "${H}/sbin/slapdd" start ; fi
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" start ; fi
  "${H}/sbin/nginxd" start
  if [[ -e "${H}/mysql/sandboxes/gitlab/start" ]] ; then
    "${H}/mysql/sandboxes/gitlab/start"
  fi
  "${H}/sbin/redisd" start
  "${H}/sbin/gitlabd" start
  if [[ -e "${H}/sbin/mcrond" ]] ; then "${H}/sbin/mcrond" start ; fi
  ;;
'stop')
  "${H}/sbin/sshd" stop
  if [[ -e "${H}/sbin/slapdd" ]] ; then "${H}/sbin/slapdd" stop ; fi
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" stop ; fi
  "${H}/sbin/nginxd" stop
  "${H}/sbin/gitlabd" stop
  "${H}/sbin/redisd" stop
  if [[ -e "${H}/mysql/sandboxes/gitlab/stop" ]] ; then
    "${H}/mysql/sandboxes/gitlab/stop"
  fi
  if [[ -e "${H}/sbin/mcrond" ]] ; then "${H}/sbin/mcrond" stop ; fi

  ;;
'restart')
  "${H}/sbin/sshd" restart
  if [[ -e "${H}/sbin/slapdd" ]] ; then "${H}/sbin/slapdd" restart ; fi
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" restart ; fi
  "${H}/sbin/nginxd" restart
  if [[ -e "${H}/mysql/sandboxes/gitlab/restart" ]] ; then
    "${H}/mysql/sandboxes/gitlab/restart"
  fi
  "${H}/sbin/redisd" restart
  "${H}/sbin/gitlabd" restart
;;
'status')
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" status ; fi
  "${H}/sbin/sshd" status
  if [[ -e "${H}/sbin/slapdd" ]] ; then "${H}/sbin/slapdd" status ; fi
  "${H}/sbin/nginxd" status
  "${H}/sbin/redisd" status
  if [[ -e "${H}/mysql/sandboxes/gitlab/status" ]] ; then
    "${H}/mysql/sandboxes/gitlab/status"
  fi
  if [[ -e "${H}/sbin/mcrond" ]] ; then "${H}/sbin/mcrond" status ; fi
  ;;
'test')
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" test ; fi
  "${H}/sbin/nginxd" test
  ;;
'reload')
  if [[ -e "${H}/sbin/ctld" ]] ; then "${H}/sbin/ctld" reload ; fi
  "${H}/sbin/nginxd" reload
  "${H}/sbin/gitlabd" reload
  ;;
*)
  echo "usage: ${H}/sbin/demod {start|stop|restart|status|test|reload}"
  ;;
esac

