#!/bin/bash

function usage() {
 echo
 echo "Usage: enc <string> <filename>"
 echo "will generate '$H/.crypt/${ce_iv}/<filename>.enc' with the encoded result"
 echo
exit
}

if [ $# -lt 2 ]
then
  usage
  exit 1
fi

if [[ ! ${ce_key128} || ! ${ce_iv} ]] ; then
  echo "ce_key128 or ce_iv global environment variable missing. No encoding possible."
  exit 1
fi

file="$2"
mkdir -p "${H}/.crypt/${ce_iv}"
echo "$1" | openssl enc -aes-128-cbc -K ${ce_key128} -out "${H}/.crypt/${ce_iv}/${file}.enc" -iv ${ce_iv} -base64
