#!/bin/sh

envfile="${H}/.gnupg/gpg-agent.env"
if test -f "$envfile" && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
    #echo "cat envfile: '$(cat "$envfile")'"
    eval "$(cat "$envfile")"
else
    echo "start gpg-agent"
    eval "$(gpg-agent --daemon --write-env-file "$envfile")"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement

"${H}/bin/gpg2" "$@"
