#! /bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=${DIR%/*}
# echo DIR=$DIR
cd "${DIR}"
H="${DIR}"
source "${DIR}/.bashrc" --force
echo HOME=$HOME $H
# exit 0

# http://stackoverflow.com/questions/8211844/get-exit-code-for-command-in-bash-ksh
eval perl $H/git/test_sync_roundtrip.pl
ret_code=$?
exit ${ret_code}
