#!/bin/bash

arg=""
if [[ "$1" == "-d" || "$1" == "-dd" ]] ; then arg=$1 ; shift ; fi
if [[ ! -d "$1" ]] ; then 
  echo -e "\e[01;31m === ERRORS: $1 directory doesn't exist === \e[0m"
  exit 1
fi
find "$1/" -type l -print0 | while read -d $'\0' file
do
  lfile="${file#$1/}"
  if [[ "${lfile}" != "" ]] ; then 
    echo "tldd ${lfile}"  
    tldd ${arg} "${lfile}" 
  fi
done
