#!/bin/bash

cmd="${1}"
shift

if [[ ! -e "${HB}/${cmd}" ]] ; then
  if [[ -e "/usr/bin/${cmd}" ]] ; then "/usr/bin/${cmd}" "$@" ;
  elif [[ -e "/usr/sbin/${cmd}" ]] ; then "/usr/sbin/${cmd}" "$@" ;
  else 
    echo -e "\e[1;31mUnknown command '${cmd}'\e[0m"; exit 1
  fi
fi
