#!/bin/bash

function rdiff() {
  local fullFilePathOri="$1"
  local fullFilePathDst="$2"
  local _rdiff="$3"

  fullFilePathDst=$(readlink -f "${fullFilePathDst}") 
  if [[ -e "${fullFilePathDst}" ]] ; then
    fullFilePathDstCpl="${fullFilePathDst/${H}/${H}/.cpl/tpl_checks}"
    mkdir -p "${fullFilePathDstCpl%/*}"
    echo "cp -f '${fullFilePathDst}' '${fullFilePathDstCpl}.tpl_ori'"
    cp -f "${fullFilePathDst}" "${fullFilePathDstCpl}.tpl_ori"
    "${H}/sbin/usrcmd/repl_tpl" "${fullFilePathOri}" "${fullFilePathDstCpl}.tpl_val"
    local rdiff_local=$(diff "${fullFilePathDstCpl}.tpl_ori" "${fullFilePathDstCpl}.tpl_val")
    #echo ${rdiff_local}
  else
    echo "warning: no '${fullFilePathDst}' to compare to."
    local rdiff_local=""
  fi

  eval ${_rdiff}="'${rdiff_local}'"
}
