#!/bin/bash

cp  "${H}/.cpl/src/git/contrib/credential/netrc/git-credential-netrc" "${HULA}/git/libexec/git-core"
gen_sed -i "s;/usr/bin/perl;${H}/bin/perl;g" "${HULA}/git/libexec/git-core/git-credential-netrc"
