#!/bin/bash

source "${H}/sbin/usrcmd/get_tpl_value"


get_tpl_value "${H}/.envs.private" "@DOWNSTREAM_URL_HGIT@" downstream_url

if [[ "${downstream_url}" == "" ]] ; then 
  #echo "no downstream_url."
  exit 0
fi

get_tpl_value "${H}/.envs.private" "@UPSTREAM_URL_HGIT@" upstream_url

if [[ "${upstream_url}" == "" ]] ; then
  #echo "no upstream_url."
  exit 0
fi

git config --global --unset credential.helper
logfn=log_"$(date +%Y%m%d -d "today")"
logf="${H}/mcron/logs/${logfn}"
mkdir -p "${H}/mcron/logs"
ln -fs "logs/${logfn}" "${H}/mcron/log"

#echo "Check if anything new comes from upstream '${downstream_url}', before pushing it back to downstream"
repos=$(git --git-dir=${H}/repositories/gitolite-admin.git show master:conf/gitolite.conf | grep "repo " | grep -v "testing" | grep -v "gitolite-admin")
while read arepo; do
  arepo=${arepo#* }
  if [[ "${arepo#@}" == "${arepo}" ]] ; then
    # echo "arepo='${arepo}'"
    ggit="git --git-dir=${H}/repositories/${arepo}.git"
    #  echo "${ggit} fetch external"
    exturl=$(${ggit} config --local --get remote.external.url)
    # echo "exturl='${exturl}'"
    if [[ "${exturl#*@}" != "${exturl}" ]] ; then
      exturl="https://projextrdr:projextrdr@${exturl#*@}"
    else
      exturl="https://projextrdr:projextrdr@${exturl#*//}"
    fi
    # echo "exturl for repo '${arepo}': external='${exturl}'"
    if [[ "${exturl}" == "https://projextrdr:projextrdr@" ]] ; then
      exturl="https://projextrdr:projextrdr@${upstream_url#*//}${arepo}.git"
      # echo "set exturl for external: '${exturl}'"
      ${ggit} remote add external ${exturl}
    fi

    chelper=$(${ggit} config --local --get credential.helper)
    if [[ "${cchelper}" == "" || "${chelper#netrc -}" == "${chelper}" ]] ; then
      $(${ggit} config --local credential.helper 'netrc -f ${H}/mcron/projextrdr.netrc.asc')
    fi
    aref=""
    if [[ -e "${H}/repositories/${arepo}.git/refs/heads/master_ext" ]] ; then
      aref=$(cat "${H}/repositories/${arepo}.git/refs/heads/master_ext")
    fi


    if [[ ${exturl#*/hgit/}" != "${exturl} ]] ; then
      r="${exturl#*/hgit/}"
      exturl="${exturl%/hgit/*}/h2git/${r}"
    fi
    fetch="${ggit} fetch ${exturl} master:master_ext"
    #echo ${fetch}
    fetchres=$(${ggit} fetch ${exturl} master:master_ext 2>&1)
    if [[ ${fetchres} != "" ]]; then
      echo "${fetch}" >> ${logf}
      echo "${fetchres}" >> ${logf}
    fi
    aref2=""
    if [[ -e "${H}/repositories/${arepo}.git/refs/heads/master_ext" ]] ; then
      aref2=$(cat "${H}/repositories/${arepo}.git/refs/heads/master_ext")
    fi
    # aref2=$(cat "${H}/repositories/${arepo}.git/refs/heads/master_ext")
    fh=$(cat "${H}/repositories/${arepo}.git/FETCH_HEAD")
    # echo "FETCH_HEAD='${fh}', refs/heads/master_ext='${aref}' => '${aref2}"
    if [[ "${aref}" != "${aref2}" && "${fh#${aref2}}" != "${fh}" ]] ; then
      dwnurl="${downstream_url}${arepo}.git"
      if [[ "${dwnurl#*@}" != "${dwnurl}" ]] ; then
        dwnurl="https://projextrdr:projextrdr@${dwnurl#*@}"
      else
        dwnurl="https://projextrdr:projextrdr@${dwnurl#*//}"
      fi

      if [[ ${dwnurl#*/hgit/}" != "${dwnurl} ]] ; then
        r="${dwnurl#*/hgit/}"
        dwnurl="${dwnurl%/hgit/*}/h2git/${r}"
      fi

      push="${ggit} push --force ${dwnurl} master_ext:master_ext"
      #echo "${push}"
      #pushres=""
      pushres=$(${ggit} push --force ${dwnurl} master_ext:master_ext 2>&1)
      if [[ ${pushres} != "" ]]; then
        echo "${push}" >> ${logf}
        echo "${pushres}" >> ${logf}
      fi
    fi
  fi
done < <(echo "${repos}")

git config --global credential.helper netrc
