#! /bin/bash

if [[ ! -e "${HULA}/openssh" ]] ; then
  aln=$(find "${HULA}" -maxdepth 1  -type d -name "openssh*")
  aln=${aln##*/}
  # echo "D: aln='${aln}'"
  ln -fs "${aln}" "${HULA}/openssh"
fi
auser=$(id -nu)
aps=$(ps -ef|grep ${auser}|grep "${H}/usr/local/apps/openssh/sbin/sshd"|grep -v grep|awk '{print $2}')
afps=""
if [[ -e "${H}/usr/local/apps/openssh/var/run/sshd.pid" ]] ; then 
  afps=$(cat "${H}/usr/local/apps/openssh/var/run/sshd.pid")
fi

# echo "aps ${aps}, afps ${afps}"

case "$1" in

'start')
  if [[ "$aps" == "" ]] ; then
    echo starting sshd
    "${H}/usr/local/apps/openssh/sbin/sshd" -f "${H}/.ssh/cnf"
  else
    echo "sshd already started, process ${aps}"
  fi
  ;;
'stop')
  if [[ "$aps" != "" ]] ; then
    echo stopping sshd
    kill -9 "${aps}"
    rm -f "${H}/usr/local/apps/openssh/var/run/sshd.pid"
  else
    echo "sshd already stopped"
  fi
  ;;
'restart')
  sshd stop
  sshd start
;;
'debug')
  sshd stop
  echo "starting sshd in a one-shot debug session (logs on stdout)"
  "${H}/usr/local/apps/openssh/sbin/sshd" -d -f "${H}/.ssh/cnf"
;;
'status')
  if [[ "${aps}" == "" ]] ; then
    echo "sshd is stopped"
  else
    echo "sshd running, process ${aps}"
  fi
  if [[ "${afps}" != "${aps}" ]] ; then
    echo "Warning, the sshd pid recorded ~/usr/local/apps/openssh/var/run/sshd.pid _${afps}_ is not the same than the running one: ${aps}"
  fi
  ;;
'test')
  "${H}/usr/local/apps/openssh/sbin/sshd" -T -f "${H}/.ssh/cnf"
;;
*)
  echo "usage: ${H}/sbin/sshd {start|stop|restart|status|test|debug}"
  ;;
esac

