#!/bin/bash
MY_DIR=$(dirname $(readlink -f $0))
#echo "MY_DIR='${MY_DIR}'"
echo "compiling test_sleep.c"
mkdir -p "${MY_DIR}/bin"
gcc "${MY_DIR}/test_sleep.c" -o "${MY_DIR}/bin/test_sleep"
echo "running test_sleep"
"${MY_DIR}/bin/test_sleep"
res=$(echo $?)
echo "result test_sleep: ${res}"
